@Echo OFF
if not exist %systemdrive%\Admins\ md %systemdrive%\Admins\
echo ------------------------------------ > %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx101\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx102\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx110\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx111\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx115\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx120\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx121\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx122\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx123\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx124\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx125\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx126\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx127\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx128\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx129\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx130\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx131\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx132\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx133\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx134\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx135\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx136\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx137\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx138\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx139\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx140\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx141\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx142\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx143\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx144\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx145\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx160\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx161\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx162\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx163\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
type "\\atlctx164\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
REM echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
REM type "\\wpnctx011\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
REM echo ------------------------------------ >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
REM type "\\wpnctx012\c$\Admins\proxysettings.txt" >> %systemdrive%\Admins\WinHTTPsetting_Citrix.txt
%systemdrive%\Admins\WinHTTPsetting_Citrix.txt