@Echo Off
REM **********************************************************************************************************************
REM 
REM    Located in each center's folder is a sub-folder called "Administrator". This folder allows the 
REM    following user access for a domain groups "BudgetUsers", "ACCT", and the center's Administrator group.
REM
REM **********************************************************************************************************************
md "D:\Documents\Facility\605 Rosewood\Administrator\Budget2016"
md "D:\Documents\Facility\606 Southern\Administrator\Budget2016"
md "D:\Documents\Facility\607 Wave Crest\Administrator\Budget2016"
md "D:\Documents\Facility\608 Panama City\Administrator\Budget2016"
md "D:\Documents\Facility\609 Citronelle\Administrator\Budget2016"
md "D:\Documents\Facility\610 Arcadia\Administrator\Budget2016"
md "D:\Documents\Facility\612 Boynton\Administrator\Budget2016"
md "D:\Documents\Facility\614 Grand Boulevard\Administrator\Budget2016"
md "D:\Documents\Facility\615 Accentia\Administrator\Budget2016"
md "D:\Documents\Facility\618 Kissimmee\Administrator\Budget2016"
md "D:\Documents\Facility\621 Chipola\Administrator\Budget2016"
md "D:\Documents\Facility\622 GlenCove\Administrator\Budget2016"
md "D:\Documents\Facility\626 Willow Trace\Administrator\Budget2016"
md "D:\Documents\Facility\627 Flagler\Administrator\Budget2016"
md "D:\Documents\Facility\628 Oakbrook\Administrator\Budget2016"
md "D:\Documents\Facility\629 DeBary\Administrator\Budget2016"
md "D:\Documents\Facility\630 Coastal H&R\Administrator\Budget2016"
md "D:\Documents\Facility\631 Seaside\Administrator\Budget2016"
md "D:\Documents\Facility\632 Parkside\Administrator\Budget2016"
md "D:\Documents\Facility\633 Bayside Manor\Administrator\Budget2016"
md "D:\Documents\Facility\634 Specialty Center\Administrator\Budget2016"
md "D:\Documents\Facility\635 Bay Breeze\Administrator\Budget2016"
md "D:\Documents\Facility\636 Silvercrest\Administrator\Budget2016"
md "D:\Documents\Facility\637 Lake Eustis\Administrator\Budget2016"
md "D:\Documents\Facility\638 Windsor\Administrator\Budget2016"
md "D:\Documents\Facility\639 Royal\Administrator\Budget2016"
md "D:\Documents\Facility\640 Lake Placid\Administrator\Budget2016"
md "D:\Documents\Facility\641 Longwood\Administrator\Budget2016"
md "D:\Documents\Facility\642 Heritage\Administrator\Budget2016"
md "D:\Documents\Facility\644 Salerno\Administrator\Budget2016"
md "D:\Documents\Facility\645 Margate\Administrator\Budget2016"
md "D:\Documents\Facility\646 Winter Park\Administrator\Budget2016"
md "D:\Documents\Facility\647 Suwannee\Administrator\Budget2016"
md "D:\Documents\Facility\648 Fountainhead\Administrator\Budget2016"
md "D:\Documents\Facility\649 Berkshire\Administrator\Budget2016"
md "D:\Documents\Facility\657 Brynwood\Administrator\Budget2016"
md "D:\Documents\Facility\658 Glen Oaks\Administrator\Budget2016"
md "D:\Documents\Facility\659 Riverchase\Administrator\Budget2016"
md "D:\Documents\Facility\671 Singing River\Administrator\Budget2016"
md "D:\Documents\Facility\672 Shelby\Administrator\Budget2016"
md "D:\Documents\Facility\673 Dixie White House\Administrator\Budget2016"
md "D:\Documents\Facility\674 Greenbough\Administrator\Budget2016"
md "D:\Documents\Facility\675 Lakeside\Administrator\Budget2016"
md "D:\Documents\Facility\677 Ocean Springs\Administrator\Budget2016"
md "D:\Documents\Facility\678 Pineview\Administrator\Budget2016"
md "D:\Documents\Facility\679 Boyington\Administrator\Budget2016"