@Echo Off
md "D:\Documents\Facility\605 Rosewood\Marketing"
md "D:\Documents\Facility\606 Southern Lifestyles\Marketing"
md "D:\Documents\Facility\607 Carnegie\Marketing"
md "D:\Documents\Facility\608 PCNC\Marketing"
md "D:\Documents\Facility\609 Citronelle\Marketing"
md "D:\Documents\Facility\610 Arcadia\Marketing"
md "D:\Documents\Facility\612 Boynton\Marketing"
md "D:\Documents\Facility\614 DHCC\Marketing"
md "D:\Documents\Facility\615 Tampa\Marketing"
md "D:\Documents\Facility\618 Kissimmee\Marketing"
md "D:\Documents\Facility\621 Chipola\Marketing"
md "D:\Documents\Facility\622 GlenCove\Marketing"
md "D:\Documents\Facility\626 Willow Trace\Marketing"
md "D:\Documents\Facility\627 Flagler\Marketing"
md "D:\Documents\Facility\628 LaBelle\Marketing"
md "D:\Documents\Facility\629 DeBary\Marketing"
md "D:\Documents\Facility\630 Coastal H&R\Marketing"
md "D:\Documents\Facility\631 Manor on the Green\Marketing"
md "D:\Documents\Facility\632 DeLand\Marketing"
md "D:\Documents\Facility\633 Bayside Manor\Marketing"
md "D:\Documents\Facility\634 Specialty Center\Marketing"
md "D:\Documents\Facility\635 Bay Breeze\Marketing"
md "D:\Documents\Facility\636 Silvercrest\Marketing"
md "D:\Documents\Facility\637 Lake Eustis\Marketing"
md "D:\Documents\Facility\638 Windsor\Marketing"
md "D:\Documents\Facility\639 Royal\Marketing"
md "D:\Documents\Facility\640 Lake Placid\Marketing"
md "D:\Documents\Facility\641 Longwood\Marketing"
md "D:\Documents\Facility\642 Heritage\Marketing"
md "D:\Documents\Facility\644 Salerno\Marketing"
md "D:\Documents\Facility\645 Margate\Marketing"
md "D:\Documents\Facility\646 Winter Park\Marketing"
md "D:\Documents\Facility\647 Suwannee\Marketing"
md "D:\Documents\Facility\648 Fountainhead\Marketing"
md "D:\Documents\Facility\649 Berkshire\Marketing"
md "D:\Documents\Facility\657 Brynwood\Marketing"
md "D:\Documents\Facility\658 Glen Oaks\Marketing"
md "D:\Documents\Facility\659 Riverchase\Marketing"
md "D:\Documents\Facility\671 Singing River\Marketing"
md "D:\Documents\Facility\672 Shelby\Marketing"
md "D:\Documents\Facility\673 Dixie White House\Marketing"
md "D:\Documents\Facility\674 Greenbough\Marketing"
md "D:\Documents\Facility\675 Lakeside\Marketing"
md "D:\Documents\Facility\677 Ocean Springs\Marketing"
md "D:\Documents\Facility\678 Pineview\Marketing"
md "D:\Documents\Facility\679 Boyington\Marketing"
